In [91]:
import numpy as np

# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
- Addition of 2 in all the element
- Multiply 3 with all the elements
- Divide every element by 2

In [93]:
a = np.array([0, 1, 2, 3, 4])

In [95]:
print(a + 2)

[2 3 4 5 6]


In [97]:
print(a * 3)

[ 0  3  6  9 12]


In [99]:
print(a / 2)

[0.  0.5 1.  1.5 2. ]


# Q.2 Questions on Basic NumPy Array:
- Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
- Find the most frequent value and their indice(s) in the following arrays:
    - x = np.array([1,2,3,4,5,1,2,1,1,1])
    - y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [101]:
arr = np.array([1, 2, 3, 4, 5])

In [103]:
print(np.flip(arr))

[5 4 3 2 1]


In [105]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
freq = np.bincount(x).argmax()
print("Most frequent values:", freq)
print("Their indices:", np.where(x == freq)[0])

Most frequent values: 1
Their indices: [0 5 7 8 9]


In [107]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq = np.bincount(y).argmax()
print("Most frequent values:", freq)
print("Their indices:", np.where(y == freq)[0])

Most frequent values: 1
Their indices: [0 1 2]


# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
- Access 1st row, 2nd column
- Access 3rd row, 1st column

In [109]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [111]:
arr[0][1]

20

In [113]:
arr[2][0]

70

# Q.4 Write program to create an 1-D NumPy array named "Your Name" with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [115]:
siddartha = np.linspace(10, 100, 25)

print("Array:", siddartha)
print("Dimension:", siddartha.ndim)
print("Shape:", siddartha.shape)
print("Total Size:", siddartha.size)
print("Data Type:", siddartha.dtype)
print("Total Bytes:", siddartha.nbytes)

siddartha_t = siddartha.reshape(25, 1)
print("Transpose with reshape:", siddartha_t)

siddartha_t_direct = siddartha.T
print("Transpose with T:", siddartha_t_direct)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension: 1
Shape: (25,)
Total Size: 25
Data Type: float64
Total Bytes: 200
Transpose with reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose with T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


# Q5. Create a 2-D Array of three rows and four columns, named ucs420_your_name with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_your_name. Resize the array to two rows and three columns and name it as resized_ ucs420_your_name.

In [121]:
ucs420_siddartha = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
mean_val = np.mean(ucs420_siddartha)
median_val = np.median(ucs420_siddartha)
max_val = np.max(ucs420_siddartha)
min_val = np.min(ucs420_siddartha)
unique = np.unique(ucs420_siddartha)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Unique:", unique)

reshaped_ucs420_siddartha = ucs420_siddartha.reshape(4, 3)
print("Reshaped:", reshaped_ucs420_siddartha)

copy = ucs420_siddartha.copy()

resized_ucs420_siddartha = np.resize(copy, (2,3))
print("Resized:", resized_ucs420_siddartha)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized: [[10 20 30]
 [40 50 60]]
